service: lambda-test-list
app: lambda-test-list

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  memorySize: 516
  timeout: 500

functions:
  lambda_test_list:
    handler: handler.lambda_test_list
    events:
      - http:
          path: lambda_test_list
          method: get
    layers:
      - ${cf:lambda-tests-layer-dev.FeaturesLayerExport}
      - ${cf:lambda-selenium-layer-dev.AllureLayerExport}
